[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
program = { version = "0.1.0", path = "../program", features = ["no-entrypoint"] }
solana-client = "2.1.0"
solana-sdk = "2.1.0"
